In [18]:
import pandas as pd
import numpy as np
import csv
import re

In [19]:
anl = pd.read_pickle('anl_df.pkl')
anl

,MMS ID,OCN,material type,perm_lib,perm_loc,gov_doc_flag,holdings_id,barcode
0,9962906580001701,(OCoLC)8972711,Quarto,TWILS,GEN,0,22521173440001701,
0,9962902330001701,(OCoLC)70132630,,TMATH,PER,0,22521192330001701,
0,9962935740001701,(OCoLC)29095895,,TSCI,PER,0,22521329290001701,
0,9962937210001701,(OCoLC)7634800,,ZMLAC,GEN,0,22521314840001701,
0,9962886460001701,(OCoLC)12598315,,DUMD,UMDGS,0,22521077960001701,
...,...,...,...,...,...,...,...,...
0,9924142430001701,(OCoLC)33958994,,TWILS,GEN,0,22356288370001701,
0,9923852390001701,(OCoLC)228504482,,TMAGR,PER,0,22355234590001701,
0,9924320810001701,(OCoLC)26375117,Quarto,TWILS,CLS,0,22356913320001701,
0,9924279090001701,(OCoLC)786126187,Folio,TMUSI,MSC,0,22356754440001701,
0,9924417770001701,(OCoLC)288960515,,TWILS,EASF,0,22357306070001701,

In [20]:
#replace empty values with NaN
anl = anl.apply(lambda x: x.str.strip()).replace('', np.nan)
anl

,MMS ID,OCN,material type,perm_lib,perm_loc,gov_doc_flag,holdings_id,barcode
0,9962906580001701,(OCoLC)8972711,Quarto,TWILS,GEN,0,22521173440001701,NaN
0,9962902330001701,(OCoLC)70132630,NaN,TMATH,PER,0,22521192330001701,NaN
0,9962935740001701,(OCoLC)29095895,NaN,TSCI,PER,0,22521329290001701,NaN
0,9962937210001701,(OCoLC)7634800,NaN,ZMLAC,GEN,0,22521314840001701,NaN
0,9962886460001701,(OCoLC)12598315,NaN,DUMD,UMDGS,0,22521077960001701,NaN
...,...,...,...,...,...,...,...,...
0,9924142430001701,(OCoLC)33958994,NaN,TWILS,GEN,0,22356288370001701,NaN
0,9923852390001701,(OCoLC)228504482,NaN,TMAGR,PER,0,22355234590001701,NaN
0,9924320810001701,(OCoLC)26375117,Quarto,TWILS,CLS,0,22356913320001701,NaN
0,9924279090001701,(OCoLC)786126187,Folio,TMUSI,MSC,0,22356754440001701,NaN
0,9924417770001701,(OCoLC)288960515,NaN,TWILS,EASF,0,22357306070001701,NaN

In [21]:
#count items in the following lmich dataframe to make sure the correct number of rows dropped out
lmich = anl[anl['perm_lib'].str.contains('lmich|DTWED|DAILR|DNRRI|DCED', case=False)]
lmich

,MMS ID,OCN,material type,perm_lib,perm_loc,gov_doc_flag,holdings_id,barcode
0,9952730540001701,(OCoLC)22859001,NaN,DNRRI,UMDNR,0,22476883040001701,250387-1002
0,9943709750001701,(OCoLC)2070387,NaN,DNRRI,UMDNR,0,22439862840001701,34814-1001
0,9917803730001701,(OCoLC)161627,NaN,DNRRI,UMDNR,0,22329670330001701,3943-1001
0,9951407900001701,(OCoLC)7845885,NaN,DNRRI,UMDNR,1,22471385080001701,66326-1001
0,9958019910001701,(OCoLC)37492111,NaN,DNRRI,UMDNR,0,22499747590001701,268802-1002
...,...,...,...,...,...,...,...,...
0,9919430870001701,(OCoLC)926892515,NaN,DAILR,UMDAI,1,22336696110001701,319530011475655
0,9962764370001701,(OCoLC)17485597,Quarto,LMICH,MGD,1,22651241480001701,30000000132450
0,9959006350001701,(OCoLC)109692,NaN,DAILR,UMDAI,0,22503973650001701,31953001027277T
0,9928821510001701,(OCoLC)5234627,NaN,DNRRI,UMDNR,0,22375856210001701,55712-1001
0,9912665750001701,(OCoLC)351283,NaN,DAILR,UMDAI,1,22307925370001701,319530011476821

In [22]:
#insert code to drop libraries we don't want since I didn't do it within Alma this time
dropped_lmich = anl[~anl['perm_lib'].str.contains('lmich|DTWED|DAILR|DNRRI|DCED', case=False)]
dropped_lmich

,MMS ID,OCN,material type,perm_lib,perm_loc,gov_doc_flag,holdings_id,barcode
0,9962906580001701,(OCoLC)8972711,Quarto,TWILS,GEN,0,22521173440001701,NaN
0,9962902330001701,(OCoLC)70132630,NaN,TMATH,PER,0,22521192330001701,NaN
0,9962935740001701,(OCoLC)29095895,NaN,TSCI,PER,0,22521329290001701,NaN
0,9962937210001701,(OCoLC)7634800,NaN,ZMLAC,GEN,0,22521314840001701,NaN
0,9962886460001701,(OCoLC)12598315,NaN,DUMD,UMDGS,0,22521077960001701,NaN
...,...,...,...,...,...,...,...,...
0,9924142430001701,(OCoLC)33958994,NaN,TWILS,GEN,0,22356288370001701,NaN
0,9923852390001701,(OCoLC)228504482,NaN,TMAGR,PER,0,22355234590001701,NaN
0,9924320810001701,(OCoLC)26375117,Quarto,TWILS,CLS,0,22356913320001701,NaN
0,9924279090001701,(OCoLC)786126187,Folio,TMUSI,MSC,0,22356754440001701,NaN
0,9924417770001701,(OCoLC)288960515,NaN,TWILS,EASF,0,22357306070001701,NaN

In [23]:
#if all looks good, make dropped_lmich = anl dataframe
anl = dropped_lmich
anl

,MMS ID,OCN,material type,perm_lib,perm_loc,gov_doc_flag,holdings_id,barcode
0,9962906580001701,(OCoLC)8972711,Quarto,TWILS,GEN,0,22521173440001701,NaN
0,9962902330001701,(OCoLC)70132630,NaN,TMATH,PER,0,22521192330001701,NaN
0,9962935740001701,(OCoLC)29095895,NaN,TSCI,PER,0,22521329290001701,NaN
0,9962937210001701,(OCoLC)7634800,NaN,ZMLAC,GEN,0,22521314840001701,NaN
0,9962886460001701,(OCoLC)12598315,NaN,DUMD,UMDGS,0,22521077960001701,NaN
...,...,...,...,...,...,...,...,...
0,9924142430001701,(OCoLC)33958994,NaN,TWILS,GEN,0,22356288370001701,NaN
0,9923852390001701,(OCoLC)228504482,NaN,TMAGR,PER,0,22355234590001701,NaN
0,9924320810001701,(OCoLC)26375117,Quarto,TWILS,CLS,0,22356913320001701,NaN
0,9924279090001701,(OCoLC)786126187,Folio,TMUSI,MSC,0,22356754440001701,NaN
0,9924417770001701,(OCoLC)288960515,NaN,TWILS,EASF,0,22357306070001701,NaN

In [24]:
#count items in the following badzmlac dataframe to make sure the correct number of rows dropped out
badzmlac = anl[anl['perm_loc'].str.contains('CARN|MANN|MPL|MPLN|NONX|SLLN|SPP|SPPN|DCED|DNRRI|DAILR|DTWED', case=False, na=False)]
badzmlac

,MMS ID,OCN,material type,perm_lib,perm_loc,gov_doc_flag,holdings_id,barcode
0,9962964010001701,(OCoLC)859902,NaN,ZMLAC,MPL,1,22521436430001701,31951M011692013
0,9933043480001701,(OCoLC)4035570,NaN,ZMLAC,MPL,0,22394138250001701,31951M013301329
0,9937695850001701,(OCoLC)2479098,NaN,ZMLAC,MPL,0,22414627560001701,31951M01121549R
0,9932924640001701,(OCoLC)4351566,NaN,ZMLAC,MPL,0,22393657850001701,31951M01315990M
0,9959685940001701,(OCoLC)251378,NaN,ZMLAC,MPL,0,22506806570001701,31951M01154682S
...,...,...,...,...,...,...,...,...
0,9936364110001701,(OCoLC)215708,NaN,ZMLAC,MPL,0,22408782120001701,31951M01217493X
0,9938400770001701,(OCoLC)2136356,NaN,ZMLAC,MPL,1,22417432480001701,31951M010946596
0,9950598250001701,(OCoLC)1923830,NaN,ZMLAC,MPL,0,22468171510001701,31951M01294265D
0,9951176520001701,(OCoLC)3438,NaN,ZMLAC,MPL,0,22470522960001701,31951M01151184N
0,9958075850001701,(OCoLC)14808032,NaN,ZMLAC,NONX,0,22725978200001701,31951M01364189E

In [25]:
#drop the bad zmlac location codes, compare difference between anl and new df to make sure it's right
#count items in the following badzmlac dataframe to make sure the correct number of rows dropped out
dropped_badzmlac = anl[~anl['perm_loc'].str.contains('CARN|MANN|MPL|MPLN|NONX|SLLN|SPP|SPPN|DCED|DNRRI|DAILR|DTWED', case=False, na=False)]
dropped_badzmlac

,MMS ID,OCN,material type,perm_lib,perm_loc,gov_doc_flag,holdings_id,barcode
0,9962906580001701,(OCoLC)8972711,Quarto,TWILS,GEN,0,22521173440001701,NaN
0,9962902330001701,(OCoLC)70132630,NaN,TMATH,PER,0,22521192330001701,NaN
0,9962935740001701,(OCoLC)29095895,NaN,TSCI,PER,0,22521329290001701,NaN
0,9962937210001701,(OCoLC)7634800,NaN,ZMLAC,GEN,0,22521314840001701,NaN
0,9962886460001701,(OCoLC)12598315,NaN,DUMD,UMDGS,0,22521077960001701,NaN
...,...,...,...,...,...,...,...,...
0,9924142430001701,(OCoLC)33958994,NaN,TWILS,GEN,0,22356288370001701,NaN
0,9923852390001701,(OCoLC)228504482,NaN,TMAGR,PER,0,22355234590001701,NaN
0,9924320810001701,(OCoLC)26375117,Quarto,TWILS,CLS,0,22356913320001701,NaN
0,9924279090001701,(OCoLC)786126187,Folio,TMUSI,MSC,0,22356754440001701,NaN
0,9924417770001701,(OCoLC)288960515,NaN,TWILS,EASF,0,22357306070001701,NaN

In [26]:
#if the counts look correct, make anl = dropped_badzmlac
anl = dropped_badzmlac
anl

,MMS ID,OCN,material type,perm_lib,perm_loc,gov_doc_flag,holdings_id,barcode
0,9962906580001701,(OCoLC)8972711,Quarto,TWILS,GEN,0,22521173440001701,NaN
0,9962902330001701,(OCoLC)70132630,NaN,TMATH,PER,0,22521192330001701,NaN
0,9962935740001701,(OCoLC)29095895,NaN,TSCI,PER,0,22521329290001701,NaN
0,9962937210001701,(OCoLC)7634800,NaN,ZMLAC,GEN,0,22521314840001701,NaN
0,9962886460001701,(OCoLC)12598315,NaN,DUMD,UMDGS,0,22521077960001701,NaN
...,...,...,...,...,...,...,...,...
0,9924142430001701,(OCoLC)33958994,NaN,TWILS,GEN,0,22356288370001701,NaN
0,9923852390001701,(OCoLC)228504482,NaN,TMAGR,PER,0,22355234590001701,NaN
0,9924320810001701,(OCoLC)26375117,Quarto,TWILS,CLS,0,22356913320001701,NaN
0,9924279090001701,(OCoLC)786126187,Folio,TMUSI,MSC,0,22356754440001701,NaN
0,9924417770001701,(OCoLC)288960515,NaN,TWILS,EASF,0,22357306070001701,NaN

In [27]:
whoops = anl[anl['perm_lib'].str.contains('LMICH')]
whoops

Empty DataFrame
Columns: [MMS ID, OCN, material type, perm_lib, perm_loc, gov_doc_flag, holdings_id, barcode]
Index: []

In [28]:
mfiche = anl[anl['material type'].str.contains('Mfiche', case=False, na=False)]
mfiche

,MMS ID,OCN,material type,perm_lib,perm_loc,gov_doc_flag,holdings_id,barcode
0,9963326950001701,(OCoLC)25104191,Mfiche,TWILS,GOVUM,1,22523456610001701,B630683
0,9963332180001701,(OCoLC)25970202,Mfiche,TWILS,GOVUM,1,22523510410001701,B631496
0,9963349460001701,(OCoLC)25556033,Mfiche,TWILS,GOVUM,1,22523531420001701,B631136
0,9963340690001701,(OCoLC)23229516,Mfiche,TWILS,GOVUM,1,22523488210001701,B630493
0,9963339570001701,(OCoLC)25970067,Mfiche,TWILS,GOVUM,1,22523483310001701,B631478
...,...,...,...,...,...,...,...,...
0,9924216840001701,(OCoLC)26859765,Mfiche,TWILS,GOVUM,1,22356511790001701,B632650
0,9924215560001701,(OCoLC)28166763,Mfiche,TWILS,GOVUM,1,22356527480001701,B633723
0,9924212100001701,(OCoLC)26883108,Mfiche,TWILS,GOVUM,1,22356535420001701,B633205
0,9924185730001701,(OCoLC)26822119,Mfiche,TWILS,GOVUM,1,22356390460001701,B632548
0,9924186990001701,(OCoLC)26638764,Mfiche,TWILS,GOVUM,1,22356396860001701,B632122

In [29]:
#drop micro records
anl = anl[~anl['material type'].str.contains('Mfiche', case=False, na=False)]
anl

,MMS ID,OCN,material type,perm_lib,perm_loc,gov_doc_flag,holdings_id,barcode
0,9962906580001701,(OCoLC)8972711,Quarto,TWILS,GEN,0,22521173440001701,NaN
0,9962902330001701,(OCoLC)70132630,NaN,TMATH,PER,0,22521192330001701,NaN
0,9962935740001701,(OCoLC)29095895,NaN,TSCI,PER,0,22521329290001701,NaN
0,9962937210001701,(OCoLC)7634800,NaN,ZMLAC,GEN,0,22521314840001701,NaN
0,9962886460001701,(OCoLC)12598315,NaN,DUMD,UMDGS,0,22521077960001701,NaN
...,...,...,...,...,...,...,...,...
0,9924142430001701,(OCoLC)33958994,NaN,TWILS,GEN,0,22356288370001701,NaN
0,9923852390001701,(OCoLC)228504482,NaN,TMAGR,PER,0,22355234590001701,NaN
0,9924320810001701,(OCoLC)26375117,Quarto,TWILS,CLS,0,22356913320001701,NaN
0,9924279090001701,(OCoLC)786126187,Folio,TMUSI,MSC,0,22356754440001701,NaN
0,9924417770001701,(OCoLC)288960515,NaN,TWILS,EASF,0,22357306070001701,NaN

In [30]:
#make sure there's nothing weird in this output
anl['perm_lib'].unique()

array(['TWILS', 'TMATH', 'TSCI', 'ZMLAC', 'DUMD', 'TMAGR', 'TAND', 'TCOS',
       'TMUSI', 'TNRL', 'TBIOM', 'TLAW', 'TZDS', 'CUMC', 'MBRIG', 'TBWAN',
       'TVET', 'AINTE', 'TARCH', 'TLAKE', 'TJOUR', 'TAHL', 'TINTE',
       'MNUDS', 'DINTE', 'CINTE'], dtype=object)

In [31]:
#these are all currenlty held so we batch assign CH to them
anl = anl.assign(holding_status='CH')
anl

,MMS ID,OCN,material type,perm_lib,perm_loc,gov_doc_flag,holdings_id,barcode,holding_status
0,9962906580001701,(OCoLC)8972711,Quarto,TWILS,GEN,0,22521173440001701,NaN,CH
0,9962902330001701,(OCoLC)70132630,NaN,TMATH,PER,0,22521192330001701,NaN,CH
0,9962935740001701,(OCoLC)29095895,NaN,TSCI,PER,0,22521329290001701,NaN,CH
0,9962937210001701,(OCoLC)7634800,NaN,ZMLAC,GEN,0,22521314840001701,NaN,CH
0,9962886460001701,(OCoLC)12598315,NaN,DUMD,UMDGS,0,22521077960001701,NaN,CH
...,...,...,...,...,...,...,...,...,...
0,9924142430001701,(OCoLC)33958994,NaN,TWILS,GEN,0,22356288370001701,NaN,CH
0,9923852390001701,(OCoLC)228504482,NaN,TMAGR,PER,0,22355234590001701,NaN,CH
0,9924320810001701,(OCoLC)26375117,Quarto,TWILS,CLS,0,22356913320001701,NaN,CH
0,9924279090001701,(OCoLC)786126187,Folio,TMUSI,MSC,0,22356754440001701,NaN,CH
0,9924417770001701,(OCoLC)288960515,NaN,TWILS,EASF,0,22357306070001701,NaN,CH

In [32]:
#because we store condition in item note 1 and these have no items we assume condition should be blank
anl = anl.assign(condition='')
anl

,MMS ID,OCN,material type,perm_lib,perm_loc,gov_doc_flag,holdings_id,barcode,holding_status,condition
0,9962906580001701,(OCoLC)8972711,Quarto,TWILS,GEN,0,22521173440001701,NaN,CH,
0,9962902330001701,(OCoLC)70132630,NaN,TMATH,PER,0,22521192330001701,NaN,CH,
0,9962935740001701,(OCoLC)29095895,NaN,TSCI,PER,0,22521329290001701,NaN,CH,
0,9962937210001701,(OCoLC)7634800,NaN,ZMLAC,GEN,0,22521314840001701,NaN,CH,
0,9962886460001701,(OCoLC)12598315,NaN,DUMD,UMDGS,0,22521077960001701,NaN,CH,
...,...,...,...,...,...,...,...,...,...,...
0,9924142430001701,(OCoLC)33958994,NaN,TWILS,GEN,0,22356288370001701,NaN,CH,
0,9923852390001701,(OCoLC)228504482,NaN,TMAGR,PER,0,22355234590001701,NaN,CH,
0,9924320810001701,(OCoLC)26375117,Quarto,TWILS,CLS,0,22356913320001701,NaN,CH,
0,9924279090001701,(OCoLC)786126187,Folio,TMUSI,MSC,0,22356754440001701,NaN,CH,
0,9924417770001701,(OCoLC)288960515,NaN,TWILS,EASF,0,22357306070001701,NaN,CH,

In [33]:
#drop barcodes here as they're not needed
anl2 =anl[anl['barcode'].isnull()]
anl2

,MMS ID,OCN,material type,perm_lib,perm_loc,gov_doc_flag,holdings_id,barcode,holding_status,condition
0,9962906580001701,(OCoLC)8972711,Quarto,TWILS,GEN,0,22521173440001701,NaN,CH,
0,9962902330001701,(OCoLC)70132630,NaN,TMATH,PER,0,22521192330001701,NaN,CH,
0,9962935740001701,(OCoLC)29095895,NaN,TSCI,PER,0,22521329290001701,NaN,CH,
0,9962937210001701,(OCoLC)7634800,NaN,ZMLAC,GEN,0,22521314840001701,NaN,CH,
0,9962886460001701,(OCoLC)12598315,NaN,DUMD,UMDGS,0,22521077960001701,NaN,CH,
...,...,...,...,...,...,...,...,...,...,...
0,9924142430001701,(OCoLC)33958994,NaN,TWILS,GEN,0,22356288370001701,NaN,CH,
0,9923852390001701,(OCoLC)228504482,NaN,TMAGR,PER,0,22355234590001701,NaN,CH,
0,9924320810001701,(OCoLC)26375117,Quarto,TWILS,CLS,0,22356913320001701,NaN,CH,
0,9924279090001701,(OCoLC)786126187,Folio,TMUSI,MSC,0,22356754440001701,NaN,CH,
0,9924417770001701,(OCoLC)288960515,NaN,TWILS,EASF,0,22357306070001701,NaN,CH,

In [37]:
ht_prep = anl2.rename(index=str, columns={"OCN":"OCLC #", "MMS ID":"Partner's Local System ID", "condition":"Condition",
                                       "gov_doc_flag":"Government Documents Indicator", "holding_status":"Holding status"})
ht_prep

,Partner's Local System ID,OCLC #,material type,perm_lib,perm_loc,Government Documents Indicator,holdings_id,barcode,Holding status,Condition
0,9962906580001701,(OCoLC)8972711,Quarto,TWILS,GEN,0,22521173440001701,NaN,CH,
0,9962902330001701,(OCoLC)70132630,NaN,TMATH,PER,0,22521192330001701,NaN,CH,
0,9962935740001701,(OCoLC)29095895,NaN,TSCI,PER,0,22521329290001701,NaN,CH,
0,9962937210001701,(OCoLC)7634800,NaN,ZMLAC,GEN,0,22521314840001701,NaN,CH,
0,9962886460001701,(OCoLC)12598315,NaN,DUMD,UMDGS,0,22521077960001701,NaN,CH,
...,...,...,...,...,...,...,...,...,...,...
0,9924142430001701,(OCoLC)33958994,NaN,TWILS,GEN,0,22356288370001701,NaN,CH,
0,9923852390001701,(OCoLC)228504482,NaN,TMAGR,PER,0,22355234590001701,NaN,CH,
0,9924320810001701,(OCoLC)26375117,Quarto,TWILS,CLS,0,22356913320001701,NaN,CH,
0,9924279090001701,(OCoLC)786126187,Folio,TMUSI,MSC,0,22356754440001701,NaN,CH,
0,9924417770001701,(OCoLC)288960515,NaN,TWILS,EASF,0,22357306070001701,NaN,CH,

In [38]:
ht_final = ht_prep[['OCLC #', 'Partner\'s Local System ID', 'Holding status', 'Condition', 'Government Documents Indicator']]
ht_final

,OCLC #,Partner's Local System ID,Holding status,Condition,Government Documents Indicator
0,(OCoLC)8972711,9962906580001701,CH,,0
0,(OCoLC)70132630,9962902330001701,CH,,0
0,(OCoLC)29095895,9962935740001701,CH,,0
0,(OCoLC)7634800,9962937210001701,CH,,0
0,(OCoLC)12598315,9962886460001701,CH,,0
...,...,...,...,...,...
0,(OCoLC)33958994,9924142430001701,CH,,0
0,(OCoLC)228504482,9923852390001701,CH,,0
0,(OCoLC)26375117,9924320810001701,CH,,0
0,(OCoLC)786126187,9924279090001701,CH,,0
0,(OCoLC)288960515,9924417770001701,CH,,0

In [69]:
ht.to_csv('umn_analytic-records_20200619.txt', sep='\t', index=False)
ht.to_pickle('umn_analytic-reords_20200619.pkl')

In [70]:
#the following lines are just some doublechecks
ht.shape

(266819, 5)

In [74]:
ht['Government Documents Indicator'] = 1

/Users/martinpatrick/opt/anaconda3/envs/marcive/lib/python3.7/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [2]:
anl = pd.read_csv('umn_analytic-records_20200619.txt', sep='\t')

In [3]:
anl["OCLC #"].nunique()

252829

In [4]:
anl["Partner's Local System ID"].nunique()

253682